//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomotolog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DentalForm
    {
        public int IDDentalForm { get; set; }
        public int PatientID { get; set; }
        public int TeethID { get; set; }
        public byte[] Date { get; set; }
        public string Discription { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Teeth Teeth { get; set; }
    }
}
