//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomotolog.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StomotologEntities : DbContext
    {
        public StomotologEntities()
            : base("name=StomotologEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergy { get; set; }
        public virtual DbSet<DentalForm> DentalForm { get; set; }
        public virtual DbSet<Diagnoses> Diagnoses { get; set; }
        public virtual DbSet<Extract> Extract { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<PatAlle> PatAlle { get; set; }
        public virtual DbSet<PatDiag> PatDiag { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teeth> Teeth { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
