//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomotolog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatDiag
    {
        public int IDPatDiag { get; set; }
        public int PatientID { get; set; }
        public int DiagnosisID { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
