//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomotolog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int IDShedule { get; set; }
        public int PatientID { get; set; }
        public System.DateTime Date { get; set; }
        public string Сomplaints { get; set; }
        public string Results { get; set; }
        public string LaborСosts { get; set; }
        public Nullable<int> DiagnosisID { get; set; }
        public string Complications { get; set; }
        public string Stage { get; set; }
        public string ICDcode { get; set; }
        public System.TimeSpan Time { get; set; }
        public int UserID { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
